### ISSUE TITLE
incidencia

### ISSUE THREAD

**Issue by alu0101020730** [ULL-ESIT-PL-1920/p3-t1-handling-events-alu0101020730#2]
- imagnes de gh pages en local el modulo
- imagenes de jekyll en local

**Comment by alu0101020730** [comment]
Imagenes de jekyll en local y modulo de gh-pages funcionando 
El modulo de gh-pages me cambia la estructura de la rama gh-pages, asi que lo ejecuté, saqué caputura y lo restablecí al estado original
@crguezl

**Comment by crguezl** [comment]
OK
